
package SafeStepZ;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.ValueMarker;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

public class AnalyseForm extends javax.swing.JFrame {
    static Connection conn=null;
    PreparedStatement ps=null;
    ResultSet rs=null;
    String sol="Normal";
    public AnalyseForm(Connection conn) {
        initComponents();
         setLocationRelativeTo(null);
//        String dbname="safestepz";
//        try{
//            Class.forName("com.mysql.jdbc.Driver");
//            String sqlServer="jdbc:mysql://localhost:3306/"+dbname;
//            conn=DriverManager.getConnection(sqlServer, "safestepz", "040916030411");
//            System.out.println("Connected");
//        }
//        catch(Exception e){
//            System.out.println("Connection Error");
//        }
        AnalyseForm.conn = conn;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        stationname = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        bridgeno = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        graph = new javax.swing.JButton();
        solution = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        normal = new javax.swing.JTextField();
        threshold = new javax.swing.JTextField();
        upperthreshold = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        constructedyear = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        psn = new javax.swing.JTextField();
        pbn = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        one = new javax.swing.JTextField();
        two = new javax.swing.JTextField();
        three = new javax.swing.JTextField();
        seven = new javax.swing.JTextField();
        eight = new javax.swing.JTextField();
        six = new javax.swing.JTextField();
        five = new javax.swing.JTextField();
        four = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        three3 = new javax.swing.JTextField();
        two2 = new javax.swing.JTextField();
        one1 = new javax.swing.JTextField();
        four4 = new javax.swing.JTextField();
        five5 = new javax.swing.JTextField();
        six6 = new javax.swing.JTextField();
        seven7 = new javax.swing.JTextField();
        eight8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(53, 33, 89));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SafeStepZ/Assets/Images/Logosmall.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 4, 4, new java.awt.Color(255, 204, 0)));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 70));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 0));
        jLabel3.setText("SAFE");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 110, 50));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("STEPZ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 130, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SafeStepZ/Assets/Images/sidepanel.jpg"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 30, 188));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bridge NO :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 120, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 110, 10));

        stationname.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "VIRAR", "VASAI", "BHAYANDER", "BORIVALI", "ANDHERI", "BANDRA", "DADAR", "ELPHINSTONE", "MUMBAI CENTRAL", "CHURCHGATE" }));
        stationname.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                stationnameItemStateChanged(evt);
            }
        });
        stationname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stationnameMouseClicked(evt);
            }
        });
        stationname.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                stationnameCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                stationnameInputMethodTextChanged(evt);
            }
        });
        stationname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stationnameActionPerformed(evt);
            }
        });
        jPanel2.add(stationname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 200, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Station Name :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 120, 30));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 90, 10));

        bridgeno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Select Station Name First>" }));
        bridgeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bridgenoActionPerformed(evt);
            }
        });
        jPanel2.add(bridgeno, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 200, 30));

        jLabel17.setFont(new java.awt.Font("Lucida Bright", 1, 30)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("STATUS");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 130, 40));

        status.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        status.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 130, 40));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 130, 10));

        graph.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        graph.setText("GRAPH Representation");
        graph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphActionPerformed(evt);
            }
        });
        jPanel2.add(graph, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 240, 50));

        solution.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        solution.setText("Solution..");
        solution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solutionActionPerformed(evt);
            }
        });
        jPanel2.add(solution, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 110, 40));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 120, 10));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 540));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel13.setText("Capacity :-");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 140, 40));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("UPPER THRESHOLD LIMIT -");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 190, 20));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("NORMAL LIMIT -");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 120, 20));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("THRESHOLD LIMIT -");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 140, 20));

        normal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(normal, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 440, 60, -1));

        threshold.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(threshold, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 470, 60, -1));

        upperthreshold.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(upperthreshold, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 500, 60, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel18.setText("Constructed  Year :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 180, 30));

        constructedyear.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        constructedyear.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(constructedyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 130, 30));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 130, 10));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel27.setText("Station -");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 120, 30));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        jLabel28.setText("Bridge No -");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 120, 30));

        psn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        psn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        psn.setText("<Present Station>");
        jPanel1.add(psn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 130, 40));

        pbn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pbn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pbn.setText("<Present Bridge No>");
        pbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbnActionPerformed(evt);
            }
        });
        jPanel1.add(pbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 130, 40));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 130, 10));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 130, 10));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(480, 280));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setText("DAYTIME");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 1, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 31, 110, 10));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Time Slots :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 41, 100, 20));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("No Of Person :");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 71, 120, 30));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel26.setText("6-8 AM");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 41, -1, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel20.setText("8-10 AM");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 41, -1, -1));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel21.setText("10-12 AM");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 41, -1, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel22.setText("12-2 PM");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 41, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setText("EVETIME");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 121, -1, -1));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 151, 110, 10));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Time Slots :");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 171, 100, 20));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("No Of Person :");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 201, 120, 30));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel19.setText("2-4 PM");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 171, -1, -1));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel23.setText("4-6 PM");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 171, -1, -1));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel24.setText("6-8 PM");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 171, -1, -1));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel25.setText("8-10 PM");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 171, -1, -1));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 111, 480, 10));

        one.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(one, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 60, -1));

        two.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });
        jPanel3.add(two, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 60, -1));

        three.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });
        jPanel3.add(three, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 60, -1));

        seven.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });
        jPanel3.add(seven, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 60, -1));

        eight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });
        jPanel3.add(eight, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 201, 60, -1));

        six.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });
        jPanel3.add(six, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 60, -1));

        five.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(five, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 60, -1));

        four.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(four, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 60, -1));

        jTabbedPane1.addTab("TODAY", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(480, 250));

        jSeparator11.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel29.setText("DAYTIME");

        jSeparator12.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel30.setText("Time Slots :");

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel31.setText("No Of Person :");

        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel32.setText("6-8 AM");

        jLabel33.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel33.setText("8-10 AM");

        jLabel34.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel34.setText("10-12 AM");

        jLabel35.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel35.setText("12-2 PM");

        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel36.setText("EVETIME");

        jSeparator13.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));

        jLabel37.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel37.setText("Time Slots :");

        jLabel38.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel38.setText("No Of Person :");

        jLabel39.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel39.setText("2-4 PM");

        jLabel40.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel40.setText("4-6 PM");

        jLabel41.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel41.setText("6-8 PM");

        jLabel42.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel42.setText("8-10 PM");

        three3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        two2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        one1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        four4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        four4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                four4ActionPerformed(evt);
            }
        });

        five5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        six6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        seven7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        eight8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(five5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(one1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(six6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(two2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(three3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(four4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(seven7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(eight8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel29)
                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(jLabel32)
                            .addGap(43, 43, 43)
                            .addComponent(jLabel33)
                            .addGap(36, 36, 36)
                            .addComponent(jLabel34)
                            .addGap(21, 21, 21)
                            .addComponent(jLabel35))
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel36)
                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(jLabel39)
                            .addGap(45, 45, 45)
                            .addComponent(jLabel40)
                            .addGap(45, 45, 45)
                            .addComponent(jLabel41)
                            .addGap(35, 35, 35)
                            .addComponent(jLabel42))
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(four4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(three3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(two2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(one1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eight8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seven7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(six6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(five5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel29)
                    .addGap(2, 2, 2)
                    .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel32)
                        .addComponent(jLabel33)
                        .addComponent(jLabel34)
                        .addComponent(jLabel35))
                    .addGap(10, 10, 10)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addComponent(jLabel36)
                    .addGap(2, 2, 2)
                    .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel39)
                        .addComponent(jLabel40)
                        .addComponent(jLabel41)
                        .addComponent(jLabel42))
                    .addGap(10, 10, 10)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("YESTERDAY", jPanel4);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 480, 260));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 70, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stationnameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_stationnameItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_stationnameItemStateChanged

    private void stationnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stationnameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_stationnameMouseClicked

    private void stationnameCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_stationnameCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_stationnameCaretPositionChanged

    private void stationnameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_stationnameInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_stationnameInputMethodTextChanged

    private void stationnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stationnameActionPerformed
        // TODO add your handling code here:
        String query;
        try{
            query="select * from bridgedetails where StationName=?";
            ps=conn.prepareStatement(query);
            ps.setString(1,stationname.getSelectedItem().toString());
            rs=ps.executeQuery();
            while(rs.next()){
                bridgeno.addItem(rs.getString("BridgeNo"));
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Select Proper Name", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_stationnameActionPerformed

    private void bridgenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bridgenoActionPerformed
        // TODO add your handling code here:
        String query;
        try{
            psn.setText(stationname.getSelectedItem().toString());
            pbn.setText(bridgeno.getSelectedItem().toString());
            query="select * from bridgedetails where BridgeNo=?";
            ps=conn.prepareStatement(query);
            ps.setString(1,bridgeno.getSelectedItem().toString());
            rs=ps.executeQuery();
            if(rs.next()){
                constructedyear.setText(rs.getString("ConstructedYear"));
                normal.setText(rs.getString("Capacity"));
                threshold.setText(rs.getString("ThresholdLimit"));
                upperthreshold.setText(rs.getString("UpperThresholdLimit"));
                status.setText(rs.getString("Status"));
                this.sol=status.getText();
            }
            query="select * from timedetails where BridgeNo=? AND Day=?";
            ps=conn.prepareStatement(query);
            ps.setString(1,bridgeno.getSelectedItem().toString());
            ps.setString(2,"Today");
            rs=ps.executeQuery();
            rs.next();
            one.setText(rs.getString("NoOfPerson"));
            rs.next();
            two.setText(rs.getString("NoOfPerson"));
            rs.next();
            three.setText(rs.getString("NoOfPerson"));
            rs.next();
            four.setText(rs.getString("NoOfPerson"));
            rs.next();
            five.setText(rs.getString("NoOfPerson"));
            rs.next();
            six.setText(rs.getString("NoOfPerson"));
            rs.next();
            seven.setText(rs.getString("NoOfPerson"));
            rs.next();
            eight.setText(rs.getString("NoOfPerson"));
            query="select * from timedetails where BridgeNo=? AND Day=?";
            ps=conn.prepareStatement(query);
            ps.setString(1,bridgeno.getSelectedItem().toString());
            ps.setString(2,"Yesterday");
            rs=ps.executeQuery();
            rs.next();
            one1.setText(rs.getString("NoOfPerson"));
            rs.next();
            two2.setText(rs.getString("NoOfPerson"));
            rs.next();
            three3.setText(rs.getString("NoOfPerson"));
            rs.next();
            four4.setText(rs.getString("NoOfPerson"));
            rs.next();
            five5.setText(rs.getString("NoOfPerson"));
            rs.next();
            six6.setText(rs.getString("NoOfPerson"));
            rs.next();
            seven7.setText(rs.getString("NoOfPerson"));
            rs.next();
            eight8.setText(rs.getString("NoOfPerson"));
        }
        catch(Exception e){
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Data Not Found", "SORRY", JOptionPane.ERROR_MESSAGE);
        }
        if(!(this.sol.equalsIgnoreCase("normal"))){
            InputStream in;
            try{
                in=new FileInputStream("src\\SafeStepZ\\audio.wav");
                AudioStream audio=new AudioStream(in);
                AudioPlayer.player.start(audio);
            }
            catch(Exception e){
                System.out.println("Audio Exception");
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_bridgenoActionPerformed

    private void graphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphActionPerformed
        // TODO add your handling code here:
        DefaultCategoryDataset dataset=new DefaultCategoryDataset();
        String a=one.getText().toString();
        String b=two.getText().toString();
        String c=three.getText().toString();
        String d=four.getText().toString();
        String e=five.getText().toString();
        String f=six.getText().toString();
        String g=seven.getText().toString();
        String h=eight.getText().toString();
        String a1=one1.getText().toString();
        String b1=two2.getText().toString();
        String c1=three3.getText().toString();
        String d1=four4.getText().toString();
        String e1=five5.getText().toString();
        String f1=six6.getText().toString();
        String g1=seven7.getText().toString();
        String h1=eight8.getText().toString();

        dataset.setValue(new Integer(a1),"Time","");
        dataset.setValue(new Integer(a),"Time","6-8 AM");
        dataset.setValue(new Integer(b1),"Time"," ");
        dataset.setValue(new Integer(b),"Time","8-10 AM");
        dataset.setValue(new Integer(c1),"Time","  ");
        dataset.setValue(new Integer(c),"Time","10-12 PM");
        dataset.setValue(new Integer(d1),"Time","    ");
        dataset.setValue(new Integer(d),"Time","12-2 PM");
        dataset.setValue(new Integer(e1),"Time","     ");
        dataset.setValue(new Integer(e),"Time","2-4 PM");
        dataset.setValue(new Integer(f1),"Time","      ");
        dataset.setValue(new Integer(f),"Time","4-6 PM");
        dataset.setValue(new Integer(g1),"Time","       ");
        dataset.setValue(new Integer(g),"Time","6-8 PM");
        dataset.setValue(new Integer(h1),"Time","        ");
        dataset.setValue(new Integer(h),"Time","8-10 PM");

        JFreeChart chart=ChartFactory.createBarChart3D("Graph","Time","No Of Person",dataset,PlotOrientation.VERTICAL,false,true,false);
        chart.setBackgroundPaint(new Color(255,204,0));
        BarRenderer renderer=null;
        CategoryPlot p=chart.getCategoryPlot();
        CategoryAxis xAxis=(CategoryAxis)p.getDomainAxis();
        xAxis.setCategoryLabelPositions(CategoryLabelPositions.UP_45);
        renderer=new BarRenderer();
        p.setRangeGridlinePaint(Color.black);
        ChartFrame frame=new ChartFrame("Bar Chart For Load",chart);
        frame.setVisible(true);
        frame.setSize(800,450);
        ValueMarker marker=new ValueMarker(new Double(threshold.getText()));
        marker.setLabel("Threshold Limit");
        marker.setLabelTextAnchor(org.jfree.ui.TextAnchor.CENTER);
        marker.setPaint(Color.WHITE);
        p.addRangeMarker(marker);
    }//GEN-LAST:event_graphActionPerformed

    private void solutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solutionActionPerformed
        // TODO add your handling code here:
        if(this.sol.equalsIgnoreCase("Normal"))
        JOptionPane.showMessageDialog(this, "Condition Is Okay", "ALL GOOD", JOptionPane.INFORMATION_MESSAGE);
        else
        JOptionPane.showMessageDialog(this, "Condition Is Bad... Send Team For Checking", "SORRY", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_solutionActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twoActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_threeActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sevenActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eightActionPerformed

    private void four4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_four4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_four4ActionPerformed

    private void pbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pbnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       new SelectionForm(conn).setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sixActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnalyseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnalyseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnalyseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnalyseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnalyseForm(conn).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox bridgeno;
    private javax.swing.JTextField constructedyear;
    private javax.swing.JTextField eight;
    private javax.swing.JTextField eight8;
    private javax.swing.JTextField five;
    private javax.swing.JTextField five5;
    private javax.swing.JTextField four;
    private javax.swing.JTextField four4;
    private javax.swing.JButton graph;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField normal;
    private javax.swing.JTextField one;
    private javax.swing.JTextField one1;
    private javax.swing.JTextField pbn;
    private javax.swing.JTextField psn;
    private javax.swing.JTextField seven;
    private javax.swing.JTextField seven7;
    private javax.swing.JTextField six;
    private javax.swing.JTextField six6;
    private javax.swing.JButton solution;
    private javax.swing.JComboBox stationname;
    private javax.swing.JTextField status;
    private javax.swing.JTextField three;
    private javax.swing.JTextField three3;
    private javax.swing.JTextField threshold;
    private javax.swing.JTextField two;
    private javax.swing.JTextField two2;
    private javax.swing.JTextField upperthreshold;
    // End of variables declaration//GEN-END:variables
}